# 键值对配置
# 
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: test
    image: busybox:1.28
    command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
    # env:
    # - name: MY_KEY
    #   valueFrom:
    #     configMapKeyRef:
    #       name: myconfigmap
    #       key: config-file
    # 使用configmap 配置env 
    # 01：一次多个value
    # envFrom:
    #   - configMapRef:
    #       name: myconfigmap
    # 02：一次一个value
    # env:
    #   - name: MY_KEY2
    #     valueFrom:
    #       configMapKeyRef:
    #         name: myconfigmap
    #         key: my-key2
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
  volumes:
  - name: config-vol
    configMap:
      name: myconfigmap
      items:
      - key: config-file
        path: log_level # 容器内的路径名，在/etc/config/log_level下存储了 key为log_level的值。
