kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: my-ingress

spec:
  ingressClassName: nginx
  rules:
  - host: mywebsite.com
    http:
      paths:
      - path: /demo
        pathType: Prefix
        backend: # service的绑定效果
          service:
            name: myweb
            port:
              number: 8080
