apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    role: test
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: my-volume
          mountPath: /var/log/nginx
    - name: busybox
      image: busybox:1.30
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh","-c","tail -f /logs/access.log"] # 初始命令，动态读取指定文件
      volumeMounts:
        - name: my-volume
          mountPath: /logs
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
        readOnly: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi