apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    role: user
spec:

  containers:
    - name: my-nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  