# 使用kind创建cluster的例子
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: false
  kubeProxy:
    extraArgs:
      proxy-args: "http://172.27.14.119:7890"
    
kubelet:
  extraEnv:
    - name: HTTPS_PROXY
      value: "https://172.27.14.119:7890"
    - name: HTTP_PROXY
      value: "http://172.27.14.119:7890"
      
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000  # 将主机 31000 端口映射到容器的 31000 端口
    hostPort: 31000
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
- role: worker
- role: worker
- role: worker
