apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  labels:
    app: myweb
    name: myweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: kubeguide/tomcat-app:v1
        name: myweb
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_SERVICE_HOST
          value: mysql
---
kind: Service
apiVersion: v1
metadata:
  name: myweb
spec:
  selector:
    app: myweb
  type: NodePort # 在任意的NodeIP:30001 可访问
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
