apiVersion: v1
kind: pod
metadata:
  namespace:
  name:
  labels:
spec:
  nodeSelector:
    nodelable-key: value
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80

