apiVersion: v1
kind: Service
metadata:
# name是在一种对象内唯一
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
   - port: 6379
     targetPort: 6379
  selector:
    app: redis
    role: leader
    tier: backend