apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: wxy
subjects:
  - kind: User # Group ServiceAccount
    name: wxy # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: wxy-role # must match the name of the Role
  apiGroup: rbac.authorization.k8s.io
