apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 8082
    targetPort: 8080
    nodePort: 8081


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - name: catport
          containerPort: 8080 # containerPort
          protocol: TCP
