apiVersion: v1
kind: Service
metadata:
  name: string
  namespace: string
  labels:
  - name: string
  annotations:
  - name: string
spec:
  selector:
  - name: string
  externalTrafficPolicy: Cluster # Cluster无论流量到达哪个节点，Kubernetes 会将流量路由到集群内任何可以处理该流量的 Pod 上。这意味着流量可能会被重定向到其他节点，而不是直接处理请求的节点。
  # Local 流量只会被路由到本地节点上运行的 Pod 上。如果流量到达的节点上没有可用的 Pod 处理请求，那么流量会被丢弃。
  type: string # ClusterIP、NodePort、LoadBalancer 类型为 NodePort时
  clusterIP: string # 类型为ClusterIP，会自动分配也可手工指定。类型为LoadBalancer，需要指定。为None时为headless Service
  sessionAffinity: string # 是否支持session，默认为None 用于无状态服务。可以选ClientIP：同一个客户端[根据ip]的请求都转发到同一个后端Pod
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 # 设置会话保持时间为10800秒
  ports:
  - name: string
    protocol: string # 协议 tcp/udp
    port: int # service 暴露的端口
    targetPort: int # 转发到Pod的端口
    nodePort: int # 当spec.type为NodePort时，指定映射到宿主机的端口
  # loadBalancerService时 以下字段由云服务商进行补充
  status:

    LoadBalancer: # 当spec.type=LoadBalancer时，设置外部负载均衡的地址
      ingress: # 外部负载均衡的设置
        ip: string # 
        hostname: string

