apiVersion: v1
kind: Service
metadata:
  name: string
  namespace: string
  labels:
  - name: string
  annotations:
  - name: string
spec:
  selector:
  - name: string
  type: string # ClusterIP、NodePort、LoadBalancer
  clusterIP: string # 类型为ClusterIP，会自动分配也可手工指定。类型为LoadBalancer，需要指定。为None时为headless Service
  sessionAffinity: string # 是否支持session，默认为None。可以选ClientIP：同一个客户端[根据ip]的请求都转发到同一个后端Pod
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 # 设置会话保持时间为10800秒
  ports:
  - name: string
    protocol: string # 协议 tcp/udp
    port: int # service 暴露的端口
    targetPort: int # 转发到Pod的端口
    nodePort: int # 当spec.type为NodePort时，指定映射到宿主机的端口
  status:
    LoadBalancer: # 当spec.type=LoadBalancer时，设置外部负载均衡的地址
      ingress: # 外部负载均衡的设置
        ip: string # 
        hostname: string

