apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 86
# 在service中不定义Label Selector 
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
- address:
  - IP: 1.2.3.4
  ports:
  - port: 86
